meta_name: "ChitChat"
meta_title: "Parce que les petits détails font les grands moments"
meta_description: "Un moyen révolutionnaire de centraliser l'information entre les parents et les nounous dans un espace intuitif et pensé pour simplifier la communication"
meta_image: "logo.png"
